# Generated by Django 4.2.2 on 2023-08-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
